### ISSUE TITLE
Internal or External access to services

### ISSUE THREAD

**Issue by Ninja-FSE** [ahembree/ansible-hms-docker#3]
How can i specify in the default.yml on each container if i want to have internal or external access?

I know i can edit docker-compose.yml.j2 file and change "middlewares=internal-ipwhitelist" to my needs but how can i do this in the vars file with something like

For Internal access

> nzbget:
>     enabled: yes
>     directory: yes
>     traefik: yes
>     expose: no

or for External access

> nzbget:
>     enabled: yes
>     directory: yes
>     traefik: yes
>     expose: yes

**Comment by ahembree** [comment]
Just to clear some things up, you're wanting to expose containers (other than Overseerr) to the public internet, is that correct? Such as exposing your nzbget container to the public internet so that people can go to `https://nzbget.<your domain>` to login to your nzbget instance?

If so, I assume you're aware of the security risks and requirements of doing this? Such as needing to configure authentication on the exposed services manually (as by default they have no authentication).

Implementing per-container public internet exposure should be pretty straightforward, I just never thought about anyone needing to expose the other containers to the public tbh (as it's a bigger security impact).

If it'd be better, would an `external-ipwhitelist` variable work? This way you can control which IP's can access your publicly exposed containers, but this would require manual updates to the IP list if your users have dynamic IPs from their ISP. Just a thought, I can likely implement both shortly.

**Comment by Ninja-FSE** [comment]
> Just to clear some things up, you're wanting to expose containers (other than Overseerr) to the public internet, is that correct? Such as exposing your nzbget container to the public internet so that people can go to https://nzbget.<your domain> to login to your nzbget instance?

Yes sir :)

> If so, I assume you're aware of the security risks and requirements of doing this? Such as needing to configure authentication on the exposed services manually (as by default they have no authentication).

Yes im aware of this and im about to try and include Authelia in your repo aswell :)

> If it'd be better, would an external-ipwhitelist variable work?

This would work, but this also needs to update the docker-compose.yml aswell?

Super thanks for the really quick replay!

**Comment by ahembree** [comment]
Just created a new branch to test implementation, I have updated the code but have not yet verified it's working correctly

Link to changes if you're interested: https://github.com/ahembree/ansible-hms-docker/compare/master...per-container-public-exposure

**Comment by ahembree** [comment]
Also good call on the required updating of the `docker-compose.yml` whenever an external-ipwhitelist value would change. Definitely don't want to possibly cause an outage by updating that variable that would impact all containers in the compose, requiring them to restart. I didn't think about that ;)

**Comment by Ninja-FSE** [comment]
This works well, thanks for the help :)

Now i gonna try and intergrate Authelia into this aswell, if a service is exposed to the internet then it should be protected by authelia auth.

**Comment by Ninja-FSE** [comment]
One question, how does this work? im trying to understand this.

In defaults.yml i want to expose Sonarr, then i choose "yes"

then in docker-compose.yml file this line is called i think?

> {% if not hms_docker_container_map['sonarr']['expose_to_public'] %}

How does that line see if it should expose sonarr or not? Does it has something todo with "if not" statement?

**Comment by Ninja-FSE** [comment]
Okey. so to add my own middleware's i need to add something like 

> {% if hms_docker_container_map['portainer']['expose_to_public'] %}
>"traefik.http.routers.portainer-{{ project_name }}.middlewares=auth@authelia"
> another-middleware-here
> and-here

Hope you understand what im trying to ask :)

**Comment by ahembree** [comment]
Yeah I think I get the idea of what you're trying to do; it sounds like you're trying to add middlewares on a per-container basis which can be easily controlled by a variable, and still have the ability to specify other middlewares.

I tried to make this project as future-proof and scalable as possible, so here's a general idea of how I would do it.

(And I'm actually in the process of adding in authelia already if you want to wait for me to push that out)

But here's an example of how you could add a simple `if` statement per container to enable authelia or not:

```jinja
...
  labels:
      - "traefik.label.here"
      - "another.traefik.label"
{% if hms_docker_container_map['portainer']['authelia'] %}
      - "traefik.http.routers.portainer-{{ project_name }}.middlewares=authelia@docker"
{% endif %}
      - "another.traefik.label"
```

This would also require you to add another "key" into the `hms_docker_container_map` per container with `authelia: no` (or `yes` to enable authelia for that container).

**Comment by ahembree** [comment]
I just pushed my basic authelia implementation to a new branch: https://github.com/ahembree/ansible-hms-docker/commit/f394b7fb4df315a5567ef5c0d17e4967d62de450

Try it out and let me know how it works. It should auto-generate a working config (for the most part). I've never used authelia before so this'll be fun to figure out.

**Comment by ahembree** [comment]
After looking at other options, I may switch it over to using [authentik](https://goauthentik.io/) instead. It has better SAML and OAuth support, whereas authelia seems to be more of a http basic-auth layer on top of things. Like if you try to login to Portainer with authelia, you'll have 2 layers of authentication.

**Comment by Ninja-FSE** [comment]
> I just pushed my basic authelia implementation to a new branch: [f394b7f](https://github.com/ahembree/ansible-hms-docker/commit/f394b7fb4df315a5567ef5c0d17e4967d62de450)
> 
> Try it out and let me know how it works. It should auto-generate a working config (for the most part). I've never used authelia before so this'll be fun to figure out.

This is awesome, gonna try this at once!



> After looking at other options, I may switch it over to using [authentik](https://goauthentik.io/) instead. It has better SAML and OAuth support, whereas authelia seems to be more of a http basic-auth layer on top of things. Like if you try to login to Portainer with authelia, you'll have 2 layers of authentication.

Never played with Authentik, only visit their webpage, gonna read up about it :)

But first im gonna try your latest push :)

**Comment by Ninja-FSE** [comment]
Trying this out, and its not working i'm affraid.

> TASK [hmsdocker : Ensure docker-compose.yml file.] ***************************************************************************************************************
> task path: /home/xxx/ansible-hms-docker/roles/hmsdocker/tasks/main.yml:52
> 

> The full traceback is:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/ansible/template/__init__.py", line 1156, in do_template
>     res = j2_concat(rf)
>   File "<template>", line 171, in root
>   File "/usr/lib/python3/dist-packages/jinja2/runtime.py", line 639, in _fail_with_undefined_error
>     raise self._undefined_exception(hint)
> jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'expose_to_public'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/ansible/plugins/action/template.py", line 150, in run
>     resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
>   File "/usr/lib/python3/dist-packages/ansible/template/__init__.py", line 1193, in do_template
>     raise AnsibleUndefinedVariable(e)
> ansible.errors.AnsibleUndefinedVariable: 'dict object' has no attribute 'expose_to_public'
> fatal: [192.168.56.10]: FAILED! => {
>     "changed": false,
>     "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'expose_to_public'"

Since im not a coder, but from what i can see maybe there is a problem in docker-compose.yml.j2 file?
To this looks like it trying to expose the service and then close it using authelia?

> {% if not hms_docker_container_map['portainer']['expose_to_public'] %}
>       - "traefik.http.routers.portainer-{{ project_name }}.middlewares=internal-ipwhitelist"
> {% if (hms_docker_container_map['authelia']['enabled'] or authelia_enabled) and traefik_ssl_enabled and hms_docker_container_map['portainer']['authelia'] %}
>       - "traefik.http.routers.portainer-{{ project_name }}.middlewares=authelia-{{ project_name }}@docker"

**Comment by ahembree** [comment]
Ahah I actually had the exact same issue when working on it last night!

Basically, if you use a custom variable file, you may need to add the `expose_to_public` manually to each container within the map like so (example using only the radarr container): 

```yml
hms_docker_container_map:
  radarr:
    enabled: yes
    directory: yes
    traefik: yes
    expose_to_public: no
...
```

But you're sorta correct! The issue isn't directly in the compose file, it is throwing an error because it expects a variable to exist in the vars file(s) and it can't render the template since it cannot find these variables. (Sorta my fault, I just realized I don't have something to handle if the variable doesn't exist)

Since it seems like you're just starting to get into this field, here's some helpful resources:
[Using markdown to style code blocks](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) (will help format your code in comments and stuff so it doesn't appear as "quoted" text)
[Using Jinja2 templates with Ansible](https://docs.ansible.com/ansible/latest/user_guide/playbooks_templating.html]) (Ansible uses Jinja2 to render template files)
[Ansible variables](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html) (Just a general ansible variable overview)

**Comment by ahembree** [comment]
Authelia has now been replaced with Authentik in https://github.com/ahembree/ansible-hms-docker/commit/dbd1c8b16971c8baaa248f4e0ddf8e13308844df.

Just follow the instructions at the bottom of the `README.md` and that should get you going in the right direction.

**Comment by Ninja-FSE** [comment]
In portainer i have the following containers running from Authentik

> authentik-proxy-homelab-local-sonarr
> authentik-server
> authentik-worker
> authentik-redis
> authentik-geoupdate
> authentik-postgresql

So far so good i think.
And in traefik i have

Http Routers:
> Host(`sonarr.homelab.local`) && PathPrefix(`/outpost.goauthentik.io`) 

Middleware:
> authentik-proxy-homelab-local-sonarr-router@docker

And the weird thing is that if i go into Sonarr's http router to see middlewares and other stuff there is no middleware to it.

I have copied the config that is generated to /opt/homelab/apps/authentik/outposts/authentik-sonarr.outpost.yml into Authentik -> Applications -> Outposts (when i created the Sonarr outpost).

**Comment by ahembree** [comment]
Hmmmm I'm not too sure what could be going on then without looking at it myself.

A valid Sonarr HTTP router in Traefik with Authentik middleware should look like this. Note that I only have HTTPS enabled and this is the `websecure-sonarr-{{ project_name }}` HTTP router within Traefik, not the router for the authentik proxy that should also be in the list.

![image](https://user-images.githubusercontent.com/8049680/173171222-47dd88a4-deb3-4e1f-8c0b-c6de1b029eab.png)

**Comment by ahembree** [comment]
Closing due to inactivity
